routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'DashboardController@index')->name('dashboard.index');

Route::resource('karyawan', 'KaryawanController');
Route::resource('kriteria', 'KriteriaController');
Route::resource('subkriteria', 'SubKriteriaController');

Route::group(['prefix' => 'bobot'], function(){
  Route::get('/', 'BobotController@index')->name('bobot.index');

  Route::group(['prefix' => 'ahp'], function(){
    Route::get('/', 'BobotController@ahp')->name('bobot.ahp');
    Route::get('form', 'BobotController@ahpform')->name('bobot.ahp.form');
    Route::post('/', 'BobotController@ahpstore')->name('bobot.ahp.store');

    Route::group(['prefix' => 'sub'], function(){
      Route::get('/{kriteriaId}/form', 'BobotController@subForm')->name('bobot.ahp.sub.form');
      Route::post('/', 'BobotController@substore')->name('bobot.ahp.sub.store');
    });
  });

  Route::group(['prefix' => 'saw'], function(){
    Route::get('/', 'BobotController@saw')->name('bobot.saw');
    Route::get('form', 'BobotController@sawform')->name('bobot.saw.form');
    Route::post('/', 'BobotController@sawstore')->name('bobot.saw.store');
  });
});

Route::group(['prefix' => 'penilaian'], function(){
  Route::get('/', 'PenilaianController@index')->name('penilaian.index');

  Route::group(['prefix' => 'ahp'], function(){
    Route::get('/', 'PenilaianAHPController@index')->name('penilaian.ahp.index');
    Route::get('/form', 'PenilaianAHPController@form')->name('penilaian.ahp.form');
    Route::get('/{id}/view', 'PenilaianAHPController@view')->name('penilaian.ahp.view');
    Route::post('/', 'PenilaianAHPController@store')->name('penilaian.ahp.store');
  });

  Route::group(['prefix' => 'saw'], function(){
    Route::get('/', 'PenilaianSAWController@index')->name('penilaian.saw.index');
    Route::get('/form', 'PenilaianSAWController@form')->name('penilaian.saw.form');
    Route::get('/{id}/view', 'PenilaianSAWController@view')->name('penilaian.saw.view');
    Route::post('/', 'PenilaianSAWController@store')->name('penilaian.saw.store');
  });
});

resources/views/layout/alert.blade.php
@if(session('success'))
<div class="alert alert-success alert-dismissible fade show" role="alert">
  {{ session('success') }}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
@endif

@if(session('warning'))
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  {{ session('warning') }}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
@endif

@if(session('danger'))
<div class="alert alert-danger alert-dismissible fade show" role="alert">
  {{ session('danger') }}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
@endif

resources/views/layout/header.blade.php
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.css">

<style>
  .dataTable{
    font-size: .8em;
  }
</style>

<title>SPK</title>

resources/views/layout/javascript.blade.php
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.js"></script>

<script type="text/javascript">
	$(document).ready(function(){
		$('.dataTable').DataTable();
	});
</script>

resources/views/layout/navbar.blade.php
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <div class="container">
    <a class="navbar-brand" href="#">SPK</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link" href="{{ route('dashboard.index') }}">Dashboard</a>

        <div class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="masterDropdown" role="button" data-toggle="dropdown">Master</a>

          <div class="dropdown-menu" aria-labelledby="masterDropdown">
            <a class="dropdown-item" href="{{ route('karyawan.index') }}">Karyawan</a>
            <a class="dropdown-item" href="{{ route('kriteria.index') }}">Kriteria</a>
            <a class="dropdown-item" href="{{ route('subkriteria.index') }}">Sub Kriteria</a>
            <a class="dropdown-item" href="{{ route('bobot.index') }}">Bobot</a>
          </div>
        </div>

        <a class="nav-item nav-link" href="{{ route('penilaian.index') }}">Penilaian</a>
      </div>
    </div>
  </div>
</nav>